### PR TITLE
fix: use new Coralogix API endpoint

### LINKED ISSUE #413: Use new Coralogix API endpoint
As described here: https://coralogix.com/docs/developer-portal/apis/log-ingestion/coralogix-rest-api-bulk/

Not only the described endpoints changed, but also the payload: instead of having a separate `logEntries` property, all entries should be passed as an array.

### PR DESCRIPTION
**Pull request by dominique-pfister**
fix #413

### CODE REVIEW

File: src/index.js [hunk 1]
```diff
@@ -21,6 +22,28 @@ import { mapSubsystem } from './subsystem.js';
...
+ * @param {UniversalContext} context the context of the universal serverless function
+ * @returns input
+ */
+async function getInput(context) {
+  const { invocation: { event } } = context;
+
+  /* c8 ignore next 3 */
+  if (process.env.HLX_DEV_SERVER_HOST) {
+    return context.data;
+  } else {
```
Comment (dominique-pfister) [inline src/index.js:37]: add code to test locally with `devserver`

**Review by tripodsan — APPROVED** [review]
