### PR TITLE
fix: send unprocessed messages to DLQ

### LINKED ISSUE #16: Unprocessed log entries should be kept
From time to time, log entries are not accepted by coralogix (either connection reset or malformed). If this happens, log entries should be stored in a DLQ.

### PR DESCRIPTION
**Pull request by dominique-pfister**
fix #16

### CODE REVIEW

File: src/coralogix.js [hunk 1]
```diff
@@ -81,21 +81,9 @@ export class CoralogixLogger {
         body: JSON.stringify(payload),
       }));
       if (!resp.ok) {
-        let msg = `Failed to send logs with status ${resp.status}: ${await resp.text()}`;
-        if (resp.status === 400) {
-          msg = `${msg}\nlogEntries: ${JSON.stringify(logEntries, 0, 2)}`;
-        }
-        return new Response(msg, { status: resp.status });
+        throw Error(`Failed to send logs with status ${resp.status}: ${await resp.text()}`);
```
Comment (dominique-pfister) [inline src/coralogix.js:84]: this service doesn't have an API gateway, so we generally no longer send `Response`s bad throw up to AWS.

**Review by tripodsan — APPROVED** [review]
